/**
 * Banner Loader
 * 为 JS/TS 文件添加版权注释
 */
module.exports = function bannerLoader(source) {
  // 获取 loader 配置的选项
  const options = this.getOptions() || {};
  const banner = options.banner || 'Generated by Custom Loader';

  // 在文件头部添加注释
  const comment = `/**\n * ${banner}\n * Build Time: ${new Date().toISOString()}\n */\n`;

  // 返回添加注释后的内容
  return comment + source;
};
